import fs from "node:fs";
import path from "node:path";
import {
  ADOBE_STOCK_SELECTORS_PATH,
  AUTOMATION_LOG_PATH,
  DATA_DIR,
  DESCRIPTIONS_PATH,
  DOWNLOADS_DIR,
  IMAGE_REGISTRY_PATH,
  LOGS_DIR,
  ROOT,
  SESSION_STATE_PATH,
  STAGING_DIR,
  TREND_DATA_PATH,
  UPSCALER_STATE_PATH,
} from "../project_paths";

type JsonRecord = Record<string, unknown>;

type SessionState = {
  session_date?: string;
  current_step?: string;
  loop_index?: number;
  current_description_index?: number;
  images_created_count?: number;
  images_downloaded_count?: number;
  downloaded_images?: DownloadedImage[];
  handoff_to_02_upscaler?: JsonRecord;
};

type DownloadedImage = {
  media_name: string;
  saved_path: string;
  suggested_filename?: string;
  downloaded_at?: string;
  project_id?: string;
};

type Description = {
  id: number;
  trend_id: number;
  trend_topic: string;
  series_slot: string;
  aspect_ratio: string;
  prompt_text: string;
  commercial_tags: string[];
};

type Trend = {
  id: number;
  topic: string;
  category: string;
  commercial_use_cases?: string[];
  visual_keywords?: string[];
};

type MetadataBlueprint = {
  mediaName: string | null;
  title: string;
  category: string;
  fileType: string;
  keywords: string[];
  promptId: number;
  seriesSlot: string;
};

const BLUEPRINTS: MetadataBlueprint[] = [
  {
    mediaName: "2b9589b6-7ba8-4ae7-9818-2f528fd04528",
    title: "Sustainable AI Data Center with Energy Dashboards",
    category: "Technology",
    fileType: "Photos",
    keywords: [
      "AI data center",
      "sustainable infrastructure",
      "server racks",
      "liquid cooling",
      "energy dashboard",
      "grid resilience",
      "renewable power",
      "cloud computing",
      "engineering team",
      "enterprise technology",
      "cooling lines",
      "data hall",
      "power monitoring",
      "green tech",
      "clean energy",
      "high efficiency",
      "modern facility",
      "semiconductor",
      "infrastructure management",
      "operations center",
      "B2B marketing",
      "technology banner",
      "future computing",
      "climate tech",
      "photorealistic",
    ],
    promptId: 1,
    seriesSlot: "16A_establishing",
  },
  {
    mediaName: "8c853ccd-1bdc-4e2b-bd59-b43cf313803c",
    title: "AI Infrastructure Engineer in Sustainable Server Facility",
    category: "Technology",
    fileType: "Photos",
    keywords: [
      "data center engineer",
      "gloved hand",
      "power monitoring",
      "server hardware",
      "close-up",
      "shallow depth of field",
      "energy analytics",
      "industrial metal",
      "sustainable tech",
      "IT infrastructure",
      "data hall",
      "equipment maintenance",
      "control interface",
      "engineering",
      "cloud operations",
      "enterprise",
      "cooling system",
      "digital dashboard",
      "B2B marketing",
      "technology concept",
      "clean lighting",
      "high detail",
      "modern facility",
      "renewable energy",
      "photorealistic",
    ],
    promptId: 2,
    seriesSlot: "16B_close_up",
  },
  {
    mediaName: "208f5a48-e8d3-486a-98fc-0ce6ee0b70a8",
    title: "AI Data Center Manager Leading Energy Briefing",
    category: "Technology",
    fileType: "Photos",
    keywords: [
      "data center manager",
      "energy load briefing",
      "cross-functional team",
      "sustainable facility",
      "inclusive leadership",
      "modern AI center",
      "operations meeting",
      "enterprise strategy",
      "women in tech",
      "engineering team",
      "grid-aware infrastructure",
      "glowing metrics",
      "calm confidence",
      "business presentation",
      "technology leadership",
      "clean facility",
      "renewable energy",
      "photorealistic",
      "horizontal banner",
      "climate tech",
      "infrastructure management",
      "workplace diversity",
      "server room",
      "power optimization",
      "modern office",
    ],
    promptId: 4,
    seriesSlot: "16D_mood_variant",
  },
  {
    mediaName: "7d841f80-e2a9-4256-aa3f-a871a8286b6d",
    title: "AI Data Center Operations Desk Overhead View",
    category: "Technology",
    fileType: "Photos",
    keywords: [
      "data center planning",
      "overhead view",
      "tablet dashboards",
      "power grid diagram",
      "cooling schematic",
      "safety gear",
      "operations table",
      "infrastructure strategy",
      "technical planning",
      "clean workstation",
      "top-down composition",
      "futuristic office",
      "energy management",
      "enterprise consulting",
      "cloud infrastructure",
      "technology background",
      "business presentation",
      "data center operations",
      "sustainable computing",
      "grid resilience",
      "project management",
      "photorealistic",
      "modern workspace",
      "flat lay",
      "high detail",
    ],
    promptId: 3,
    seriesSlot: "16C_overhead",
  },
  {
    mediaName: "f7b32cc4-1d0e-406a-9aae-799e87038d21",
    title: "Confident Infrastructure Engineer in AI Facility",
    category: "Technology",
    fileType: "Photos",
    keywords: [
      "infrastructure engineer",
      "centered portrait",
      "AI server racks",
      "energy analytics",
      "sustainable facility",
      "professional lighting",
      "cloud and ESG",
      "enterprise technology",
      "Black professional",
      "data center",
      "confident expression",
      "modern workplace",
      "technology marketing",
      "B2B campaign",
      "clean background",
      "server aisle",
      "green tech",
      "infrastructure expert",
      "photorealistic",
      "square format",
      "leadership",
      "modern operations",
      "smart energy",
      "IT specialist",
      "corporate portrait",
    ],
    promptId: 5,
    seriesSlot: "1A_portrait",
  },
  {
    mediaName: "9a12e562-3946-4ce7-b7b7-db6aea960f0a",
    title: "AI Power Demand Eye Reflection Concept",
    category: "Concepts & Metaphors",
    fileType: "Photos",
    keywords: [
      "AI power demand",
      "eye reflection",
      "grid awareness",
      "server lights",
      "concept image",
      "sustainable computing",
      "data center energy",
      "futuristic realism",
      "shallow depth of field",
      "abstract technology",
      "digital dashboards",
      "energy analytics",
      "infrastructure concept",
      "enterprise innovation",
      "close-up concept",
      "photorealistic",
      "metaphor",
      "data visualization",
      "climate tech",
      "technology editorial",
      "operations insight",
      "smart grid",
      "server glow",
      "modern computing",
      "conceptual portrait",
    ],
    promptId: 6,
    seriesSlot: "1B_extreme_close_up",
  },
  {
    mediaName: "2e695b1b-dd74-448e-9672-841754bdfa50",
    title: "Sustainable Infrastructure Workspace Flat Lay",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "enterprise sustainability",
      "top-down flat lay",
      "power curves",
      "renewable notes",
      "server cooling components",
      "safety badge",
      "recycled materials",
      "clean modern look",
      "tech consulting",
      "workspace style",
      "overhead composition",
      "data center planning",
      "sustainability strategy",
      "business background",
      "photorealistic",
      "green technology",
      "operations desk",
      "modern office",
      "infrastructure design",
      "climate tech",
      "project notes",
      "tablet screen",
      "flat lay",
      "corporate marketing",
      "detail",
    ],
    promptId: 7,
    seriesSlot: "1C_flatlay",
  },
  {
    mediaName: "aa521d80-d3ac-4279-a1d0-e2246252a901",
    title: "Inclusive AI Operations Specialist Portrait",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "older East Asian specialist",
      "AI operations room",
      "sustainable infrastructure",
      "warm focused expression",
      "modern data center",
      "facilities management",
      "inclusive technology",
      "square portrait",
      "enterprise transformation",
      "server room",
      "professional lighting",
      "clean background",
      "photorealistic",
      "business use",
      "tech workforce diversity",
      "energy management",
      "operations specialist",
      "modern workplace",
      "cloud infrastructure",
      "climate tech",
      "leadership",
      "neutral attire",
      "smart facility",
      "IT operations",
      "corporate portrait",
    ],
    promptId: 8,
    seriesSlot: "1D_demographic_variant",
  },
  {
    mediaName: "30d29a47-7afa-4553-9a83-f2989300a13f",
    title: "Family Reviewing Household Budget at Dining Table",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "family budgeting",
      "household expenses",
      "inflation pressure",
      "dining table finance",
      "grocery receipts",
      "calculator",
      "laptop charts",
      "monthly budget",
      "personal finance",
      "insurance campaign",
      "cost of living",
      "home interior",
      "authentic concern",
      "modern family",
      "money management",
      "consumer stress",
      "savings plan",
      "budget review",
      "economic pressure",
      "financial planning",
      "domestic lifestyle",
      "photorealistic",
      "horizontal banner",
      "household economics",
      "banking marketing",
    ],
    promptId: 9,
    seriesSlot: "16A_establishing",
  },
  {
    mediaName: "031d17be-a925-4055-bd99-ecbe12c842ce",
    title: "Hands Comparing Grocery Receipts and Budget App",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "grocery receipts",
      "budget app",
      "calculator",
      "household finance",
      "close-up hands",
      "price comparison",
      "paper textures",
      "warm household light",
      "banking promotion",
      "savings concept",
      "expense tracking",
      "personal budgeting",
      "cost of living",
      "money management",
      "mobile finance",
      "receipt detail",
      "consumer budgeting",
      "financial literacy",
      "inflation impact",
      "shopping costs",
      "domestic economics",
      "photorealistic",
      "horizontal format",
      "fintech marketing",
      "home budget",
    ],
    promptId: 10,
    seriesSlot: "16B_close_up",
  },
  {
    mediaName: "663323f7-818b-4430-9a66-9357b750f678",
    title: "Household Budget Planning Overhead with Receipts",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "budget planning",
      "overhead receipts",
      "kitchen counter",
      "pantry items",
      "price tags",
      "budget notebook",
      "expense tablet",
      "household finance",
      "top-down composition",
      "editorial finance",
      "personal expenses",
      "consumer budgeting",
      "grocery planning",
      "cost tracking",
      "organized clutter",
      "money management",
      "family economics",
      "inflation theme",
      "flat lay finance",
      "home budgeting",
      "expense categories",
      "photorealistic",
      "overhead view",
      "banking content",
      "savings strategy",
    ],
    promptId: 11,
    seriesSlot: "16C_overhead",
  },
  {
    mediaName: "502775e4-2a48-4bc4-a60d-1a9536f14758",
    title: "Small Business Owner Checking Supply Costs",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "small business owner",
      "supply costs",
      "price update",
      "storefront office",
      "economic pressure",
      "SME finance",
      "retail pricing",
      "thoughtful mood",
      "focused owner",
      "cost management",
      "inventory planning",
      "inflation challenge",
      "shop office",
      "business budgeting",
      "entrepreneurship",
      "profit margin",
      "supply chain cost",
      "modern tools",
      "retail operations",
      "financial planning",
      "commercial banking",
      "photorealistic",
      "horizontal banner",
      "business resilience",
      "market pressure",
    ],
    promptId: 12,
    seriesSlot: "16D_mood_variant",
  },
  {
    mediaName: "ca2af536-ef06-4032-8084-24fcf781f6aa",
    title: "Mother Reviewing Monthly Expenses in Home Kitchen",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "monthly expenses",
      "household budgeting",
      "mother",
      "groceries",
      "laptop",
      "receipts",
      "calculator",
      "savings",
      "personal finance",
      "inflation",
      "family budget",
      "home kitchen",
      "expense tracking",
      "budget planning",
      "financial stress",
      "domestic life",
      "woman at home",
      "money management",
      "cost of living",
      "practical finance",
      "budget app",
      "family finances",
      "lifestyle",
      "budgeting concept",
      "photorealistic",
    ],
    promptId: 13,
    seriesSlot: "1A_portrait",
  },
  {
    mediaName: "3c6ba3c6-ad11-4b96-9cda-bb0da1e73929",
    title: "Rising Household Costs on Mobile Budgeting Dashboard",
    category: "Concepts & Metaphors",
    fileType: "Photos",
    keywords: [
      "rising costs",
      "budgeting dashboard",
      "mobile app",
      "receipt total",
      "fingertip",
      "consumer finance",
      "inflation",
      "household budget",
      "expense tracking",
      "cost pressure",
      "savings",
      "financial app",
      "close up",
      "shallow depth of field",
      "money management",
      "family expenses",
      "price increase",
      "digital finance",
      "budget planning",
      "economic pressure",
      "smartphone screen",
      "concept image",
      "personal finance",
      "photorealistic",
      "editorial",
    ],
    promptId: 14,
    seriesSlot: "1B_extreme_close_up",
  },
  {
    mediaName: "56f948d3-9f6a-410b-ba15-ab56318f4da8",
    title: "Household Budget Flat Lay with Receipts and Calculator",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "household budget",
      "flat lay",
      "receipts",
      "calculator",
      "notebook",
      "grocery list",
      "smartphone",
      "expense tracker",
      "savings",
      "personal finance",
      "budgeting tools",
      "home office",
      "expense planning",
      "cost of living",
      "family finances",
      "top down view",
      "financial organization",
      "money management",
      "inflation",
      "domestic budget",
      "clean surface",
      "blog imagery",
      "practical finance",
      "photorealistic",
      "lifestyle",
    ],
    promptId: 15,
    seriesSlot: "1C_flatlay",
  },
  {
    mediaName: "9d8ba4ea-42ab-4760-b58c-b71f5e0cc87d",
    title: "Older Arab Man Managing Family Expenses at Home",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "older Arab man",
      "family expenses",
      "home budgeting",
      "tablet",
      "receipts",
      "personal finance",
      "savings",
      "inflation",
      "cost of living",
      "money management",
      "household budget",
      "inclusive portrait",
      "financial planning",
      "domestic life",
      "calm resilience",
      "mature adult",
      "finance at home",
      "budgeting concept",
      "expense tracking",
      "family finances",
      "business concept",
      "realistic lifestyle",
      "photorealistic",
      "banking education",
      "portrait",
    ],
    promptId: 16,
    seriesSlot: "1D_demographic_variant",
  },
  {
    mediaName: "16c11a60-61b0-4b85-8ff6-5f817663fc59",
    title: "Fintech Team Monitoring Global Payment Flows",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "stablecoin payments",
      "digital payments",
      "fintech operations",
      "payment flow",
      "wallet",
      "global transactions",
      "transparent display",
      "business team",
      "finance technology",
      "modern office",
      "transaction monitoring",
      "cross border payments",
      "innovation",
      "enterprise",
      "secure payment",
      "digital currency",
      "banking technology",
      "payment platform",
      "commercial dashboard",
      "collaboration",
      "data visualization",
      "professional team",
      "future finance",
      "brand neutral",
      "photorealistic",
    ],
    promptId: 17,
    seriesSlot: "16A_establishing",
  },
  {
    mediaName: "07ff2001-1389-4056-805c-e3d33cb70f7b",
    title: "Secure Digital Wallet Approval on Smartphone",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "secure digital wallet",
      "smartphone payment",
      "contactless terminal",
      "hand close-up",
      "transaction approval",
      "fintech",
      "mobile banking",
      "payment security",
      "glowing interface",
      "card reader",
      "digital currency",
      "business technology",
      "retail payment",
      "cashless",
      "shallow depth of field",
      "app interface",
      "secure checkout",
      "innovation",
      "brand neutral",
      "photorealistic",
      "modern finance",
      "commerce",
      "electronic payment",
      "payment confirmation",
      "premium detail",
    ],
    promptId: 18,
    seriesSlot: "16B_close_up",
  },
  {
    mediaName: "45af0fd4-8fb3-42ff-b764-55faaa8f9677",
    title: "Cross Border Payments Workspace Overhead View",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "cross border payments",
      "top down",
      "fintech flat lay",
      "passport",
      "smartphone",
      "card",
      "notebook",
      "settlement diagram",
      "transaction flow",
      "digital finance",
      "international commerce",
      "business desk",
      "payment rails",
      "global transfer",
      "overhead view",
      "editorial",
      "innovation",
      "wallet",
      "secure payment",
      "minimal workspace",
      "market expansion",
      "modern office",
      "strategy",
      "brand neutral",
      "photorealistic",
    ],
    promptId: 19,
    seriesSlot: "16C_overhead",
  },
  {
    mediaName: "87d1b706-ab77-4a10-a7b2-3deddb4176a6",
    title: "Payments Strategist Presenting Faster Settlement Metrics",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "payments strategist",
      "faster settlement",
      "boardroom",
      "fintech presentation",
      "digital overlays",
      "women in business",
      "inclusive team",
      "payment metrics",
      "finance technology",
      "modern workplace",
      "global payments",
      "cross border",
      "innovation",
      "strategy meeting",
      "business campaign",
      "data visualization",
      "leadership",
      "professional",
      "brand neutral",
      "photorealistic",
      "corporate",
      "payment rails",
      "digital wallet",
      "collaboration",
      "optimism",
    ],
    promptId: 20,
    seriesSlot: "16D_mood_variant",
  },
  {
    mediaName: "2e69ad4f-3ce6-40c1-b5ec-22bbe26ee59c",
    title: "Fintech Founder Holding Digital Wallet Phone",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "fintech founder",
      "centered portrait",
      "digital wallet",
      "mobile payments",
      "payment innovation",
      "studio lighting",
      "office background",
      "startup leadership",
      "confident",
      "technology entrepreneur",
      "secure payments",
      "financial technology",
      "modern business",
      "brand neutral",
      "app marketing",
      "digital currency",
      "transaction glow",
      "professional portrait",
      "commerce",
      "innovation",
      "young adult",
      "clean background",
      "square format",
      "photorealistic",
      "payment platform",
    ],
    promptId: 21,
    seriesSlot: "1A_portrait",
  },
  {
    mediaName: "35341ac3-8a53-4685-8b8c-650ed0db1980",
    title: "Contactless Payment Card and Smartphone Close Up",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "contactless card",
      "smartphone",
      "secure payment",
      "close-up",
      "mobile wallet",
      "payment terminal",
      "shallow depth of field",
      "transaction",
      "fintech",
      "digital checkout",
      "touchless commerce",
      "card payment",
      "financial technology",
      "modern payment concept",
      "brand neutral",
      "interface reflection",
      "innovation",
      "retail payments",
      "electronic transfer",
      "premium detail",
      "business",
      "cashless",
      "smartphone screen",
      "secure commerce",
      "photorealistic",
    ],
    promptId: 22,
    seriesSlot: "1B_extreme_close_up",
  },
  {
    mediaName: "e1de3fff-04a7-4965-b6a7-2f0ae79813d4",
    title: "Minimal Fintech Desk with Wallet Screen Flat Lay",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "fintech desk",
      "top down",
      "wallet screen",
      "payment card",
      "ledger notes",
      "headphones",
      "transaction sketches",
      "startup marketing",
      "digital payments",
      "modern workspace",
      "brand neutral",
      "payment innovation",
      "financial technology",
      "business concept",
      "minimal arrangement",
      "overhead view",
      "clean design",
      "cashless",
      "digital currency",
      "commerce",
      "office desk",
      "strategy",
      "photorealistic",
      "product mockup",
      "modern finance",
    ],
    promptId: 23,
    seriesSlot: "1C_flatlay",
  },
  {
    mediaName: "76c4283d-2130-4b21-81d2-04c10ce587e6",
    title: "Elderly Japanese Advisor Explaining Digital Payments",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "elderly Japanese advisor",
      "centered portrait",
      "digital payment rails",
      "tablet",
      "trust",
      "inclusive finance",
      "senior professional",
      "fintech education",
      "modern banking",
      "payment guidance",
      "business portrait",
      "brand neutral",
      "financial literacy",
      "digital wallet",
      "technology adoption",
      "customer support",
      "clean background",
      "approachable expression",
      "cross generational",
      "innovation",
      "commerce",
      "professional attire",
      "square composition",
      "photorealistic",
      "modern finance",
    ],
    promptId: 24,
    seriesSlot: "1D_demographic_variant",
  },
  {
    mediaName: "cef08ec4-8e81-41b8-8071-94f78156942c",
    title: "Doctor and Patient Reviewing AI Screening Results",
    category: "Healthcare & Medicine",
    fileType: "Photos",
    keywords: [
      "AI screening",
      "preventive care",
      "doctor patient",
      "clinic",
      "diagnosis",
      "medical monitor",
      "healthcare innovation",
      "patient consultation",
      "screening results",
      "hospital",
      "wellness",
      "digital health",
      "clinical workflow",
      "modern medicine",
      "inclusive care",
      "physician",
      "medical technology",
      "risk visualization",
      "clean exam room",
      "reassuring",
      "professional",
      "photorealistic",
      "brand neutral",
      "healthcare marketing",
      "care team",
    ],
    promptId: 25,
    seriesSlot: "16A_establishing",
  },
  {
    mediaName: "c06c9760-05ef-4741-806e-2b9b3784c704",
    title: "Clinician Pointing to AI Risk Visualization on Monitor",
    category: "Healthcare & Medicine",
    fileType: "Photos",
    keywords: [
      "clinician hand",
      "AI risk visualization",
      "medical monitor",
      "preventive screening",
      "close up",
      "healthcare technology",
      "patient care",
      "diagnostic display",
      "clinical interface",
      "soft lighting",
      "shallow depth of field",
      "medtech",
      "hospital",
      "wellness",
      "doctor",
      "screening concept",
      "modern medicine",
      "patient support",
      "clean display",
      "non branded",
      "professional",
      "photorealistic",
      "brand neutral",
      "healthcare marketing",
      "digital diagnostics",
    ],
    promptId: 26,
    seriesSlot: "16B_close_up",
  },
  {
    mediaName: "baf13fa5-932c-4afa-ab6e-2f1b1ca48fab",
    title: "Preventive Care Workstation with Digital Triage Tools",
    category: "Healthcare & Medicine",
    fileType: "Photos",
    keywords: [
      "overhead view",
      "preventive care",
      "triage tools",
      "tablet scans",
      "stethoscope",
      "patient notes",
      "medical workstation",
      "digital health",
      "clinical desk",
      "healthcare planning",
      "clean layout",
      "blue white palette",
      "diagnostics",
      "modern medicine",
      "hospital admin",
      "wellness",
      "medical workflow",
      "top down",
      "non branded",
      "photorealistic",
      "brand neutral",
      "healthcare marketing",
      "professional",
      "care coordination",
      "editorial",
    ],
    promptId: 27,
    seriesSlot: "16C_overhead",
  },
  {
    mediaName: "8a750e02-1c61-4d9c-abc4-48d6762cd460",
    title: "Radiologists Reviewing AI Screening Workflow Together",
    category: "Healthcare & Medicine",
    fileType: "Photos",
    keywords: [
      "radiologist",
      "AI screening workflow",
      "clinical collaboration",
      "healthcare team",
      "inclusive medicine",
      "medical review",
      "bright clinic",
      "diagnostics",
      "preventive care",
      "doctor colleague",
      "supportive mood",
      "medical technology",
      "patient care",
      "hospital",
      "modern medicine",
      "professional",
      "women in healthcare",
      "non branded",
      "photorealistic",
      "brand neutral",
      "healthcare marketing",
      "team meeting",
      "workflow",
      "clinical innovation",
      "wellness",
    ],
    promptId: 28,
    seriesSlot: "16D_mood_variant",
  },
  {
    mediaName: "f6112835-843f-44e6-9a56-8e983c415d01",
    title: "Compassionate Doctor in Modern Clinic Portrait",
    category: "Healthcare & Medicine",
    fileType: "Photos",
    keywords: [
      "doctor portrait",
      "compassionate doctor",
      "modern clinic",
      "preventive care",
      "healthcare innovation",
      "diagnostic screens",
      "physician",
      "medical professional",
      "calm expression",
      "clean background",
      "wellness",
      "digital health",
      "hospital",
      "clinical setting",
      "patient care",
      "trusted care",
      "inclusive medicine",
      "non branded",
      "photorealistic",
      "brand neutral",
      "healthcare marketing",
      "square portrait",
      "professional",
      "medtech",
      "modern medicine",
    ],
    promptId: 29,
    seriesSlot: "1A_portrait",
  },
  {
    mediaName: "a0e8da50-9965-491b-b000-0853202f20b0",
    title: "Diagnostic Display Close Up with Clinician in Frame",
    category: "Healthcare & Medicine",
    fileType: "Photos",
    keywords: [
      "diagnostic display",
      "close up",
      "clinician finger",
      "AI medicine",
      "imaging patterns",
      "preventive screening",
      "medical technology",
      "shallow depth of field",
      "clinical interface",
      "non branded",
      "healthcare",
      "hospital",
      "wellness",
      "patient care",
      "digital diagnostics",
      "modern medicine",
      "screen detail",
      "professional",
      "photorealistic",
      "brand neutral",
      "medtech",
      "concept",
      "medical review",
      "visual data",
      "care",
    ],
    promptId: 30,
    seriesSlot: "1B_extreme_close_up",
  },
  {
    mediaName: "7dbc3695-b286-43bf-868a-75899f795aad",
    title: "Preventive Healthcare Tools Flat Lay",
    category: "Healthcare & Medicine",
    fileType: "Photos",
    keywords: [
      "flat lay",
      "preventive healthcare",
      "tablet scans",
      "appointment notes",
      "smart wearable",
      "medical accessories",
      "clean surface",
      "digital health",
      "clinical tools",
      "top down",
      "healthcare editorial",
      "wellness",
      "modern medicine",
      "patient care",
      "hospital",
      "diagnostics",
      "organized desk",
      "non branded",
      "photorealistic",
      "brand neutral",
      "healthcare marketing",
      "medical workflow",
      "technology",
      "care planning",
      "professional",
    ],
    promptId: 31,
    seriesSlot: "1C_flatlay",
  },
  {
    mediaName: "5634d767-4606-4889-8da9-c2243b68338a",
    title: "Hijabi Physician Using AI Clinical Interface",
    category: "Healthcare & Medicine",
    fileType: "Photos",
    keywords: [
      "hijabi physician",
      "AI clinical interface",
      "portrait",
      "inclusive healthcare",
      "preventive care",
      "doctor",
      "modern clinic",
      "medical technology",
      "warm expression",
      "soft lighting",
      "digital health",
      "wellness",
      "hospital",
      "patient care",
      "diagnostics",
      "professional portrait",
      "non branded",
      "photorealistic",
      "brand neutral",
      "healthcare marketing",
      "square format",
      "women in medicine",
      "diverse workforce",
      "modern medicine",
      "clinical innovation",
    ],
    promptId: 32,
    seriesSlot: "1D_demographic_variant",
  },
  {
    mediaName: "fbf50617-e6e8-4478-8408-d3f23707715d",
    title: "Hybrid Team Collaboration in Modern Office",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "hybrid work",
      "team collaboration",
      "modern office",
      "remote teamwork",
      "young professionals",
      "mentors",
      "video call",
      "coworking space",
      "workplace culture",
      "collaboration tools",
      "warm daylight",
      "authentic business",
      "HR marketing",
      "SaaS brand",
      "office meeting",
      "diverse team",
      "productivity",
      "professional environment",
      "future of work",
      "brand neutral",
      "photorealistic",
      "horizontal banner",
      "workplace wellbeing",
      "digital collaboration",
      "leadership",
    ],
    promptId: 33,
    seriesSlot: "16A_establishing",
  },
  {
    mediaName: "27edc836-2813-4df2-86f2-08f9d588b675",
    title: "Gen Z Employee Taking Notes in Collaborative Meeting",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "Gen Z employee",
      "close-up",
      "collaborative meeting",
      "laptop",
      "earbuds",
      "video call",
      "focused mood",
      "modern office",
      "remote work",
      "team notes",
      "workplace culture",
      "productivity",
      "professional environment",
      "young adult",
      "business technology",
      "office collaboration",
      "shallow depth of field",
      "digital workflow",
      "brand neutral",
      "photorealistic",
      "horizontal format",
      "connected work",
      "future of work",
      "meeting detail",
      "SaaS marketing",
    ],
    promptId: 34,
    seriesSlot: "16B_close_up",
  },
  {
    mediaName: "f2a5fe37-4337-4bea-85be-d385dbed9764",
    title: "Hybrid Meeting Table Overhead with Remote Participants",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "hybrid meeting",
      "overhead view",
      "laptops",
      "notebooks",
      "coffee cups",
      "wireless headphones",
      "tablet",
      "remote participants",
      "top-down composition",
      "collaboration tools",
      "workplace setup",
      "productivity",
      "office desk",
      "business meeting",
      "future of work",
      "team coordination",
      "digital collaboration",
      "brand neutral",
      "photorealistic",
      "flat lay",
      "horizontal banner",
      "modern workplace",
      "professional environment",
      "workplace culture",
      "meeting strategy",
    ],
    promptId: 35,
    seriesSlot: "16C_overhead",
  },
  {
    mediaName: "34e4b411-3bfb-42d2-993d-418ae295738c",
    title: "Young Professional Returning to Office for Mentorship",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "young professional",
      "mentorship",
      "office return",
      "collaboration",
      "diverse team",
      "wellbeing",
      "optimism",
      "candid energy",
      "modern workplace",
      "Gen Z",
      "future of work",
      "HR campaign",
      "business culture",
      "professional growth",
      "team connection",
      "office environment",
      "horizontal banner",
      "brand neutral",
      "photorealistic",
      "workplace support",
      "leadership",
      "inclusive team",
      "natural daylight",
      "productivity",
      "recruitment marketing",
    ],
    promptId: 36,
    seriesSlot: "16D_mood_variant",
  },
  {
    mediaName: "ba95f9a1-f89e-4a99-9fac-436a631aabc9",
    title: "Mixed Race Professional in Bright Coworking Portrait",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "mixed race professional",
      "centered portrait",
      "coworking space",
      "laptop",
      "thoughtful expression",
      "soft natural light",
      "hybrid work",
      "Gen Z",
      "professional portrait",
      "modern office",
      "workplace culture",
      "business branding",
      "brand neutral",
      "photorealistic",
      "square format",
      "collaboration",
      "future of work",
      "young adult",
      "productivity",
      "office lifestyle",
      "HR marketing",
      "professional environment",
      "digital collaboration",
      "clean background",
      "leadership potential",
    ],
    promptId: 37,
    seriesSlot: "1A_portrait",
  },
  {
    mediaName: "280d5130-bbf2-4e44-b734-032be9944f6f",
    title: "Hands Typing in Shared Document During Video Call",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "hands typing",
      "shared document",
      "video call",
      "glasses reflection",
      "close-up",
      "tactile detail",
      "collaboration concept",
      "hybrid work",
      "remote teamwork",
      "modern office",
      "digital workflow",
      "business technology",
      "brand neutral",
      "photorealistic",
      "shallow depth of field",
      "team communication",
      "productivity",
      "office culture",
      "future of work",
      "professional detail",
      "square format",
      "workplace wellbeing",
      "SaaS marketing",
      "focused",
      "connected work",
    ],
    promptId: 38,
    seriesSlot: "1B_extreme_close_up",
  },
  {
    mediaName: "252e6866-0807-4310-9694-29f019414059",
    title: "Hybrid Work Setup Flat Lay with Productivity Tools",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "hybrid work setup",
      "flat lay",
      "laptop",
      "notebook",
      "webcam",
      "headphones",
      "transit card",
      "coffee cup",
      "productivity tools",
      "modern desk",
      "workplace culture",
      "remote collaboration",
      "brand neutral",
      "photorealistic",
      "top-down",
      "square format",
      "office lifestyle",
      "future of work",
      "digital workflow",
      "professional environment",
      "business marketing",
      "clean desk",
      "wellbeing",
      "team communication",
      "SaaS campaign",
    ],
    promptId: 39,
    seriesSlot: "1C_flatlay",
  },
  {
    mediaName: "a36340d2-71ab-49d0-a3bd-63af821fa684",
    title: "Older Mentor Speaking with Younger Colleague",
    category: "Business",
    fileType: "Photos",
    keywords: [
      "older mentor",
      "younger colleague",
      "office corner",
      "supportive expression",
      "professional culture",
      "recruitment marketing",
      "team building",
      "inclusive workplace",
      "hybrid work",
      "Gen Z",
      "leadership",
      "career growth",
      "business portrait",
      "modern office",
      "brand neutral",
      "photorealistic",
      "square format",
      "mentorship",
      "workplace wellbeing",
      "collaboration",
      "professional environment",
      "human connection",
      "natural light",
      "HR campaign",
      "future of work",
    ],
    promptId: 40,
    seriesSlot: "1D_demographic_variant",
  },
];

const MEDIA_PROMPT_OVERRIDES: Record<string, number> = {
  "b64d5bc1-081d-46b3-a592-48b04d6822e3": 1,
  "dd2a5956-32db-4430-853b-da9438b3dd2f": 2,
  "cc4b9af1-fd2d-496e-85e8-6434e383be9c": 3,
  "2d7f035f-f357-4b03-b5e0-1d83dcc646a4": 4,
  "e604168d-f722-404c-97cb-f7b706fd0795": 5,
  "62d5903d-830a-4cd6-b351-290243d2a4bc": 6,
  "5745622a-8084-41d4-972f-38cb1cda6bb8": 7,
  "1d7819e4-75ed-49da-b31b-a188be420014": 8,
  "7898f0b8-a84a-4211-8875-f67e67bee5b0": 9,
  "3feddb9f-c13b-44bd-9b97-4e1cbc0899b6": 10,
  "c312fafb-71ac-4e7d-adcf-218df78994ef": 11,
  "e1101b8d-8987-432b-b749-c5deb356b49b": 12,
  "a66cc494-f8bc-48b3-a455-2c4327459aff": 13,
  "715f6959-1fc9-445e-aa89-0eef92805c71": 14,
  "36e3f08b-8d77-4cd0-8f95-6cd43b677fa8": 15,
  "a89326b4-462a-40b2-a91b-4747140b76a6": 16,
  "9c88b159-c247-452f-8271-3544f8347463": 17,
  "304757e4-bf6a-4d6b-9e21-d4569dbb8b12": 18,
  "59d59d8f-82ed-4bde-864b-43b0f5142609": 19,
  "0440e21d-0f6a-4a15-9b48-5b713fabfcf2": 20,
  "c7c9e071-ddeb-4248-8bd9-c1c0b05bd109": 21,
  "050126df-45f7-40f7-90b4-36abf85f2783": 22,
  "6de54bd7-55bd-40d7-96db-bc5f29d4f6c9": 23,
  "f80561b3-9fb8-4cd0-a113-f92f627fcb34": 24,
  "ace34b80-af0e-4f4b-9cb2-89d7403b610d": 25,
  "7b9cc92b-8a73-4b93-81b2-b9202c791949": 26,
  "1d4be93b-7888-476f-9844-dcc2154da5c0": 27,
  "b13e0606-2473-495f-816b-b81a9f986c65": 28,
  "0ba8de3e-f35b-485d-8584-7a9dfd9365db": 29,
  "348ee48e-b1ce-4df4-a73e-772a9d5fc6cc": 30,
  "ec57cf71-dd2f-46a5-8944-6954600b3bfd": 31,
  "d7686a78-4092-4123-87ae-8b0e7278f088": 32,
  "7f8fc96a-a6a6-41c3-990d-c976794906d8": 34,
  "1e252732-c429-483e-a8ea-ee4ff7d4bdcc": 35,
  "8cab0812-4abb-419d-9923-370bfef60a0b": 36,
  "65ca303e-d671-4ee2-827f-4bce725b1ed5": 1,
  "da86101c-d778-4ade-a8e5-0030e90bfb17": 2,
  "1741e922-baa8-4199-884f-9eb2d4cdbdc5": 4,
  "99802175-0ec0-4afe-94b6-54ff9dfd87f2": 3,
  "88424b9f-8095-421e-9175-2052149b46f9": 5,
  "c2d38c8b-79b0-4fe3-a68f-260732bd3b2d": 6,
  "4ad323da-31f3-4cd0-b9d7-da78c3c9941b": 7,
  "a667b0ba-6984-4b34-bbf2-0f492df725d7": 8,
  "f76991e5-b26a-4f0a-9e86-824d288ec731": 37,
  "085aef21-32e5-4cb3-8bc3-a11103efe2dd": 38,
  "18d81ffb-5cdb-4a1a-b2f4-28c15184927a": 39,
  "ae7b7acb-0b02-466f-a311-eeaa8ef3c0ec": 40,
};

function readJson<T>(filePath: string, fallback: T): T {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8")) as T;
  } catch {
    return fallback;
  }
}

function writeJson(filePath: string, value: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function appendLog(message: string): void {
  const now = new Date();
  const stamp = `${now.toISOString().slice(0, 10)}__${now.toTimeString().slice(0, 8)}`;
  fs.appendFileSync(AUTOMATION_LOG_PATH, `${stamp} ${message}\n`, "utf8");
}

function windowsRelative(filePath: string): string {
  return path.relative(ROOT, filePath).replaceAll("/", "\\");
}

function pngDimensions(filePath: string): { width: number; height: number } {
  const data = fs.readFileSync(filePath);
  if (data.length < 24) {
    throw new Error(`PNG too small to measure: ${filePath}`);
  }
  return {
    width: data.readUInt32BE(16),
    height: data.readUInt32BE(20),
  };
}

function assignedScale(longSide: number): number | "copy" {
  if (longSide >= 3840) return "copy";
  if (longSide >= 1921) return 2;
  if (longSide >= 1281) return 3;
  return 4;
}

function defaultUpscalerState(): JsonRecord {
  const upscaylExe = "C:\\Program Files\\Upscayl\\Upscayl.exe";
  const cliBinary = "C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin.exe";
  const modelsDir = "C:\\Program Files\\Upscayl\\resources\\models\\";
  return {
    last_updated: new Date().toISOString(),
    upscayl_exe_path: fs.existsSync(upscaylExe) ? upscaylExe : null,
    method: fs.existsSync(cliBinary) ? "cli" : "gui",
    cli_binary_path: fs.existsSync(cliBinary) ? cliBinary : null,
    models_dir: fs.existsSync(modelsDir) ? modelsDir : null,
    model_name: "ultrasharp-4x",
    output_base_folder: path.join(DOWNLOADS_DIR, "upscaled").replaceAll("/", "\\"),
    staging_base_folder: STAGING_DIR.replaceAll("/", "\\"),
    default_scale_for_ai_images: 2,
    max_scale_allowed: 4,
  };
}

function defaultAdobeStockSelectors(): JsonRecord {
  return {
    last_updated: new Date().toISOString(),
    selectors_discovered: false,
    site: "contributor.stock.adobe.com",
    selectors: {
      image_grid_thumbnail: {
        description: "Individual image thumbnail in the upload queue grid",
        trigger_required: false,
        selector: "[DISCOVERED_AT_RUNTIME]",
        discovery_strategy: "Find the grid container, then locate clickable image elements within it",
        interaction: "click to select and open right panel",
      },
      right_panel_container: {
        description: "The right metadata panel that appears when an image is selected",
        trigger_required: true,
        trigger_action: "click on any image thumbnail",
        selector: "[DISCOVERED_AFTER_TRIGGER]",
        interaction: "parent container for all metadata fields",
      },
      file_type_select: {
        description: "File type dropdown (Photos / Illustrations)",
        trigger_required: true,
        trigger_action: "click on any image thumbnail",
        selector: "[DISCOVERED_AFTER_TRIGGER]",
        interaction: "select element — use value or click option",
      },
      category_select: {
        description: "Category dropdown",
        trigger_required: true,
        trigger_action: "click on any image thumbnail",
        selector: "[DISCOVERED_AFTER_TRIGGER]",
        interaction: "select element — use value or click option",
      },
      language_select: {
        description: "Language selector",
        trigger_required: true,
        trigger_action: "click on any image thumbnail",
        selector: "[DISCOVERED_AFTER_TRIGGER]",
        interaction: "verify English is selected",
      },
      ai_generated_checkbox: {
        description: "Created using generative AI tools checkbox",
        trigger_required: true,
        trigger_action: "click on any image thumbnail",
        selector: "input[name='content-tagger-generative-ai-checkbox']",
        fallback_id: "content-tagger-generative-ai-checkbox",
        interaction: "click to check",
      },
      people_property_fictional_checkbox: {
        description: "People and Property are fictional checkbox",
        trigger_required: true,
        trigger_action: "check ai_generated_checkbox",
        selector: "[DISCOVERED_AFTER_TRIGGER]",
        interaction: "click to check",
      },
    },
  };
}

function ensureDataFiles(): void {
  fs.mkdirSync(LOGS_DIR, { recursive: true });
  if (!fs.existsSync(UPSCALER_STATE_PATH)) {
    writeJson(UPSCALER_STATE_PATH, defaultUpscalerState());
  }
  if (!fs.existsSync(ADOBE_STOCK_SELECTORS_PATH)) {
    writeJson(ADOBE_STOCK_SELECTORS_PATH, defaultAdobeStockSelectors());
  }
  if (!fs.existsSync(IMAGE_REGISTRY_PATH)) {
    writeJson(IMAGE_REGISTRY_PATH, {
      last_updated: new Date().toISOString(),
      total_images: 0,
      images: {},
    });
  }
}

function main(): void {
  ensureDataFiles();

  const session = readJson<SessionState>(SESSION_STATE_PATH, {});
  const descriptionsPayload = readJson<{ descriptions: Description[] }>(DESCRIPTIONS_PATH, { descriptions: [] });
  const trendPayload = readJson<{ trends: Trend[] }>(TREND_DATA_PATH, { trends: [] });
  const registry = readJson<{ last_updated: string; total_images: number; images: Record<string, JsonRecord> }>(
    IMAGE_REGISTRY_PATH,
    { last_updated: new Date().toISOString(), total_images: 0, images: {} },
  );

  const descriptionsById = new Map(descriptionsPayload.descriptions.map((item) => [item.id, item]));
  const trendsById = new Map(trendPayload.trends.map((item) => [item.id, item]));
  const downloadsByMedia = new Map((session.downloaded_images ?? []).map((item) => [item.media_name, item]));
  const blueprintByPromptId = new Map<number, MetadataBlueprint>();
  for (const blueprint of BLUEPRINTS) {
    if (!blueprintByPromptId.has(blueprint.promptId)) {
      blueprintByPromptId.set(blueprint.promptId, blueprint);
    }
  }

  let sidecarsWritten = 0;
  let highestPromptId = session.current_description_index ?? 0;

  for (const blueprint of BLUEPRINTS) {
    if (!blueprint.mediaName) {
      continue;
    }
    const downloaded = downloadsByMedia.get(blueprint.mediaName);
    if (!downloaded) {
      continue;
    }

    const description = descriptionsById.get(blueprint.promptId);
    if (!description) {
      continue;
    }

    const trend = trendsById.get(description.trend_id);
    const imagePath = downloaded.saved_path;
    const imageFile = path.basename(imagePath);
    const sidecarPath = path.join(path.dirname(imagePath), `${path.parse(imageFile).name}.metadata.json`);
    const dims = pngDimensions(imagePath);
    const longSide = Math.max(dims.width, dims.height);

    const sidecar = {
      image_file: imageFile,
      generated_at: downloaded.downloaded_at ?? new Date().toISOString(),
      series_slot: description.series_slot,
      aspect_ratio: description.aspect_ratio,
      trend_topic: description.trend_topic,
      trend_category: trend?.category ?? "Technology",
      loop_index: 0,
      adobe_stock_metadata: {
        title: blueprint.title,
        title_char_count: blueprint.title.length,
        keywords: blueprint.keywords,
        keyword_count: blueprint.keywords.length,
        category: blueprint.category,
        file_type: blueprint.fileType,
        created_with_ai: true,
        people_are_fictional: true,
        property_is_fictional: true,
        editorial_use_only: false,
      },
      generation_context: {
        prompt_used: description.prompt_text,
        model_used: "Nano Banana 2",
        commercial_use_cases: trend?.commercial_use_cases ?? [],
        visual_keywords_from_trend: trend?.visual_keywords ?? description.commercial_tags,
      },
      status: "ready_for_upload",
      applied_to_adobe_stock: false,
    };

    writeJson(sidecarPath, sidecar);
    sidecarsWritten += 1;

    registry.images[imageFile] = {
      source: "ai_generated",
      final_name: imageFile,
      original_name: downloaded.suggested_filename ?? imageFile,
      source_path: windowsRelative(imagePath),
      dimensions: dims,
      long_side: longSide,
      assigned_scale: assignedScale(longSide),
      metadata_sidecar: windowsRelative(sidecarPath),
      upscaled: false,
      upscaled_path: null,
      upscaled_dimensions: null,
      registered_at: downloaded.downloaded_at ?? new Date().toISOString(),
      upscaled_at: null,
      adobe_stock_status: "not_uploaded",
      trend_topic: description.trend_topic,
      series_slot: description.series_slot,
      prompt_id: blueprint.promptId,
      media_name: blueprint.mediaName,
    };
    highestPromptId = Math.max(highestPromptId, blueprint.promptId);
  }

  for (const [mediaName, downloaded] of downloadsByMedia) {
    const imageFile = path.basename(downloaded.saved_path);
    if (registry.images[imageFile]) {
      continue;
    }

    const promptId = MEDIA_PROMPT_OVERRIDES[mediaName];
    if (!promptId) {
      continue;
    }

    const template = blueprintByPromptId.get(promptId);
    const description = descriptionsById.get(promptId);
    if (!template || !description) {
      continue;
    }

    const trend = trendsById.get(description.trend_id);
    const imagePath = downloaded.saved_path;
    const sidecarPath = path.join(path.dirname(imagePath), `${path.parse(imageFile).name}.metadata.json`);
    const dims = pngDimensions(imagePath);
    const longSide = Math.max(dims.width, dims.height);

    const sidecar = {
      image_file: imageFile,
      generated_at: downloaded.downloaded_at ?? new Date().toISOString(),
      series_slot: description.series_slot,
      aspect_ratio: description.aspect_ratio,
      trend_topic: description.trend_topic,
      trend_category: trend?.category ?? "Technology",
      loop_index: session.loop_index ?? 0,
      adobe_stock_metadata: {
        title: template.title,
        title_char_count: template.title.length,
        keywords: template.keywords,
        keyword_count: template.keywords.length,
        category: template.category,
        file_type: template.fileType,
        created_with_ai: true,
        people_are_fictional: true,
        property_is_fictional: true,
        editorial_use_only: false,
      },
      generation_context: {
        prompt_used: description.prompt_text,
        model_used: "Nano Banana 2",
        commercial_use_cases: trend?.commercial_use_cases ?? [],
        visual_keywords_from_trend: trend?.visual_keywords ?? description.commercial_tags,
      },
      status: "ready_for_upload",
      applied_to_adobe_stock: false,
    };

    writeJson(sidecarPath, sidecar);
    sidecarsWritten += 1;

    registry.images[imageFile] = {
      source: "ai_generated",
      final_name: imageFile,
      original_name: downloaded.suggested_filename ?? imageFile,
      source_path: windowsRelative(imagePath),
      dimensions: dims,
      long_side: longSide,
      assigned_scale: assignedScale(longSide),
      metadata_sidecar: windowsRelative(sidecarPath),
      upscaled: false,
      upscaled_path: null,
      upscaled_dimensions: null,
      registered_at: downloaded.downloaded_at ?? new Date().toISOString(),
      upscaled_at: null,
      adobe_stock_status: "not_uploaded",
      trend_topic: description.trend_topic,
      series_slot: description.series_slot,
      prompt_id: promptId,
      media_name: mediaName,
    };
    highestPromptId = Math.max(highestPromptId, promptId);
  }

  registry.last_updated = new Date().toISOString();
  registry.total_images = Object.keys(registry.images).length;
  writeJson(IMAGE_REGISTRY_PATH, registry);

  session.current_description_index = highestPromptId;
  session.images_created_count = Math.max(session.images_created_count ?? 0, registry.total_images);
  session.images_downloaded_count = Math.max(session.images_downloaded_count ?? 0, registry.total_images);

  session.handoff_to_02_upscaler = {
    ...(session.handoff_to_02_upscaler ?? {}),
    images_ready_for_processing: true,
    ai_images_folder: path.join(DOWNLOADS_DIR, "2026-03-28").replaceAll("/", "\\"),
    manual_images_folder: path.join(DOWNLOADS_DIR, "manual").replaceAll("/", "\\"),
    images_downloaded_count: session.images_downloaded_count ?? 0,
    metadata_sidecars_written: sidecarsWritten,
    image_registry: IMAGE_REGISTRY_PATH.replaceAll("/", "\\"),
    note: "Metadata sidecars synchronized with downloaded Flow images.",
  };
  writeJson(SESSION_STATE_PATH, session);

  appendLog(`Sub-Agent D backfill complete. Wrote ${sidecarsWritten} metadata sidecars and synced image_registry.json.`);
}

main();
